version: "3.9"

services:
  build:
    container_name: node-proxy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    networks:
        - node-proxy
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./files_metadata:/app/files_metadata

networks:
  node-proxy:
    driver: bridge

